
export default [
    {
        id:1,
        postedOn : '2024-07-10',
        title: "Android Developer",
        company: 'Apple',
        type: 'Full-Time',
        experience: 'Beginner',
        location: 'Remote',
        skills: ["SwiftUI", "UiKit", "Core Data"],
        job_link: "https://www.apple.com/careers/in/",
    },
    {
        id: 2,
        postedOn: '2024-07-2',
        title: "Frontend Developer",
        type: "Full-time",
        location: "In-office",
        experience: "Fresher",
        company: "Amazon",
        skills: ["Javascript", "Nextjs", "Tailwind CSS"],
        job_link: "https://www.amazon.jobs/en/",
      },
      {
        id: 3,
        postedOn: '2024-07-05',
        title: "Android Developer",
        type: "Part-time",
        location: "Remote",
        experience: "Senior",
        company: "Facebook",
        skills: ["Kotlin", "MVVM"],
        job_link: "https://facebook.com/careers",
      },
      {
        id: 4,
        postedOn: '2024-06-01',
        title: "Developer Advocate",
        type: "Contract",
        location: "Hybrid",
        experience: "Intermediate",
        company: "Netflix",
        skills: ["web3", "Content Creation", "Community"],
        job_link: "https://jobs.netflix.com/",
      },
]
      